// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjAwPuvx4cYZfJc3QW7k_p9yi3fAO5Xo',
    appId: '1:598563455945:web:1e213dd969001eeb385e18',
    messagingSenderId: '598563455945',
    projectId: 'flutter-6890b',
    authDomain: 'flutter-6890b.firebaseapp.com',
    storageBucket: 'flutter-6890b.firebasestorage.app',
    measurementId: 'G-S29GB1880P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoI2-tmfIAFvGPB_HY4_BBalSl1ajJsw',
    appId: '1:598563455945:android:7df58da2a0b31b27385e18',
    messagingSenderId: '598563455945',
    projectId: 'flutter-6890b',
    storageBucket: 'flutter-6890b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwERt5YTOE1bNuvRRkAjPh7C-wXBoJK5A',
    appId: '1:598563455945:ios:4a060cb7ab7f0848385e18',
    messagingSenderId: '598563455945',
    projectId: 'flutter-6890b',
    storageBucket: 'flutter-6890b.firebasestorage.app',
    iosBundleId: 'com.example.provaP2',
  );
}
